version: '3.0'
services:
   node:
      build:
        context: .
        dockerfile: ./node/Dockerfile
      image: node:latest
      stdin_open: true
      tty: true
      ports:
         - "8545:8545"
         - "30302:30302"
         - "30302:30302/udp"
      networks:
         - app_net
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24