version: '3.0'
services:
   bootnode:
      build:
        context: .
        dockerfile: ./bootnode/Dockerfile
      image: bootnode:latest
      networks:
         app_net:
            ipv4_address: 172.16.238.10
      ports:
         - "30301:30301"
         - "30301:30301/udp"
   node:
      build:
        context: .
        dockerfile: ./node/Dockerfile
      image: node:latest
      stdin_open: true
      tty: true
      ports:
         - "8545:8545"
         - "30302:30302"
         - "30302:30302/udp"
      networks:
         - app_net
   miner:
      build:
         context: .
         dockerfile: ./miner/Dockerfile
      image: miner:latest
      stdin_open: true
      tty: true
      ports:
         - "30304:30304"
         - "30304:30304/udp"
      networks:
         - app_net
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24