version: '3'
services:
   bootnode:
      build:
        context: ./bootnode
      image: bootnode:latest
      networks:
         app_net:
            ipv4_address: 172.16.238.10
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24